In [1]:
import numpy as np

In [2]:
def align_depth_lstsq(pred, gt, mask):

    """

    Подбирает scale и shift через least squares: gt ≈ scale * pred + shift

    Возвращает aligned predicted depth в метрах.

    """

    pred_valid = pred[mask]

    gt_valid = gt[mask]



    A = np.stack([pred_valid, np.ones_like(pred_valid)], axis=1)

    scale, shift = np.linalg.lstsq(A, gt_valid, rcond=None)[0]



    return scale * pred + shift, scale, shift

In [3]:
def compute_depth_metrics(pred, gt, max_depth=80.0):

    """

    Стандартные метрики оценки глубины (KITTI eval protocol)

    """

    mask = (gt > 0.1) & (gt < max_depth)

    pred = pred[mask]

    gt = gt[mask]



    abs_rel = np.mean(np.abs(pred - gt) / gt)

    sq_rel = np.mean((pred - gt) ** 2 / gt)

    rmse = np.sqrt(np.mean((pred - gt) ** 2))

    rmse_log = np.sqrt(np.mean((np.log(pred) - np.log(gt)) ** 2))



    thresh = np.maximum(pred / gt, gt / pred)

    delta1 = np.mean(thresh < 1.25)

    delta2 = np.mean(thresh < 1.25 ** 2)

    delta3 = np.mean(thresh < 1.25 ** 3)



    return {

        'AbsRel': abs_rel,

        'SqRel': sq_rel,

        'RMSE': rmse,

        'RMSE_log': rmse_log,

        'δ < 1.25': delta1,

        'δ < 1.25²': delta2,

        'δ < 1.25³': delta3,

    }

## Загрузка всего и вся

In [ ]:
!gdown --folder --remaining-ok "https://drive.google.com/drive/folders/1-1606rH8lv-vf6kJ-fpH78TMu5bBExwn?usp=drive_link"

Retrieving folder contents
Retrieving folder 1G8W_tpHxmVgVUkCcpLoZ_7gKHdrTrtDr Scene01
Processing file 10US12kjZXBkIfrmy-bKnDL2XsnPJBwf0 00000.npy
Processing file 1tf73CkE4U2O8TO3qtQHwWK15Ml8lsPbZ 00001.npy
Processing file 18cOTHCB6109eekTbgDH2wd83mQzR1nv5 00002.npy
Processing file 1TTESNaeiPTKZuaZbV8ebWOVYME5MuwMp 00003.npy
Processing file 1WQ9rjSj-cFGjopMf2UDTq8CC2rDMQNO7 00004.npy
Processing file 11isWJYnLWrOLjokT_XdF--KntwNASSWG 00005.npy
Processing file 1iAA4UNCYrkNB5Wt80ezpIklSjH89pvE0 00006.npy
Processing file 1emtNgndD8W5Z4rB7HuOz0qMn8k_Ipl4P 00007.npy
Processing file 10IBR7GNyBC4nEt5jYqsOJM3WX_ilDB4C 00008.npy
Processing file 1TN_SGYo5eMp23MwRJDGzUpcN7XpZH9vg 00009.npy
Processing file 10b9KlsCALJXSbq3vH2a-r8eAcNwWxn9G 00010.npy
Processing file 16VKQhgrfhKjGZThUZfZewAx25vhkUI-o 00011.npy
Processing file 1HqBU9UzR_R5zN0JZXM8fcr0drg5m3K37 00012.npy
Processing file 1bWpHqHsd3Qk0KSZshyrxEiao3M436Gmw 00013.npy
Processing file 1A6tRk9-1grOBc73vH3wq3lhfYirbRlRX 00014.npy
Processing file 1r7EgdurAV0AN--4bQnJ9XYJLh_f2f0ID 00015.npy
Processing file 1Dbr6aT7v4Iu91moVTbbGoq7LOzOP9Fcd 00016.npy
Processing file 1wUwkS-9GnXsTv6St8GLSM4UFRCYZWbT6 00017.npy
Processing file 1D7gkVyDmpWYMK3_eyljzezAK_KnFQ6mp 00018.npy
Processing file 1Gx6hp7CiuJIxn8s4LgCpoRNAAb9N8TdI 00019.npy
Processing file 1SLufcYNuC-KcfbMqOeVUfmN21jquiNTy 00020.npy
Processing file 1BkCj3PpB3I2IzI7eb39kjJBdY24BnNcn 00021.npy
Processing file 12_eGzsTbIyq2VJ1RCXsUhlQ_WOtst11W 00022.npy
Processing file 1BUVHUu-V6PSET5sHF5SyMZTa2kR3hK71 00023.npy
Processing file 1rM-qZpn8dupC5YEgGlWKyrb2KpWiVPNz 00024.npy
Processing file 1gTgjVmVdswk_77h-dm5yiCnEsZ2TjO3q 00025.npy
Processing file 1Allkc6FglHNFdF3DfxC03lKpdP64ePQs 00026.npy
Processing file 1lZjOkjRRVPWhnMQJzhhUTLKXpMHcicgJ 00027.npy
Processing file 1LZtcAMWJJlGkNiMAY-aCp-oER5tpbkQ4 00028.npy
Processing file 1MJvftKnov3wqMH_5nD5ASs2qE9CHs3h3 00029.npy
Processing file 1QrTg17jKG6_kkaEW6gz0oym7Pr7sfrKx 00030.npy
Processing file 1ssva8fR9WwX-X3lE9XP4BCtTQqAQxaMS 00031.npy
Processing file 1_A7yZ20G8rUXp7KV4Ngd8xqqrmXu83yU 00032.npy
Processing file 1eySYGvf7mj3R-Sz_gqP7iAK2qc3zumPD 00033.npy
Processing file 1XYkvkZUO2ewF34_zatjLJd2AcXsyuZDR 00034.npy
Processing file 1X3WBypGE35ZYyJcD7ASwKTPKeKrAcZFC 00035.npy
Processing file 1VGa58VVmKSycTMIsCpWNNnLOfzECr5wu 00036.npy
Processing file 1SEG4tM4YdjZgX1SSloUiCwo3WLLX8bEO 00037.npy
Processing file 1wC4NLliBdQBYTE1KRu-36DW4DTf4jQgL 00038.npy
Processing file 1v7Cj6MSD8TVtR8WnstY1_acSruGNN4ml 00039.npy
Processing file 1ow6N0qR1xfug8GDzf0wJ-Cm-qK0BO3NQ 00040.npy
Processing file 1zcTctYwrlyKVFZsXFvqQPY8z2MdhKP_H 00041.npy
Processing file 1dt8M_L8FlTcYLzDSW_4eF6ACKNOPp9jd 00042.npy
Processing file 1IK5kLQQgmbOn5riU631uSkVSUz9hoV3Y 00043.npy
Processing file 1UmCvq9SL4RefPwL3UjO3F91NrSlcup4B 00044.npy
Processing file 17iLJjn1wRnnzvsUv9bPjG8Q6pgaNwe-G 00045.npy
Processing file 1_IangSZpjvT4ZrrznsUAYZn4z6O7tspE 00046.npy
Processing file 1kETjW65HNthkZqMbn88y5KB9WbSd_xfo 00047.npy
Processing file 1Aw5Jp5GGR0qQ0oKV3niGLAp2U-DQdoBs 00048.npy
Processing file 1gu3I58_23zrK28qz_Syg-yEcZX0aU5Jm 00049.npy
Retrieving folder 1EKZ3dYgzWDWRLKJxmdPj41LembJlicMi Scene02
Processing file 1KnMGE4j4ati5icQVB9loBqCmWRdDCoBv 00000.npy
Processing file 1M6tP-i2gyf8etlP6OW2zpDPSM_9g_Hh- 00001.npy
Processing file 1-Y2nN-zvft-nqJ4rPF5MMCyw2fEwPvBw 00002.npy
Processing file 18kx0BKr0i_WlCz7KgSMsryLSU1EpD-R1 00003.npy
Processing file 19eC738O9QqXfr6qEAMaabw9Eh_lr5Pk- 00004.npy
Processing file 1wpfpBkojgaNijYy-9rIVFumxyps5RqXS 00005.npy
Processing file 16NXEgAb6QPbmKbD8Bgxa3xE5xEjvKrvg 00006.npy
Processing file 1Tb64Jnod5rR_L2DQFDjxb0_mqGVKsgOn 00007.npy
Processing file 1kpvIJNe-5QcFlYXFIAPRCKOwZwWpGucB 00008.npy
Processing file 1XmK9tN4Gg2bxD_LRoOGLtSJ3U0QU8LFp 00009.npy
Processing file 1VAOVmbdId5k2_yca6h5bcd4YIjKP6oK5 00010.npy
Processing file 1YN4K0NXB9BkKaeGpa3SYlPNfGjCQIidy 00011.npy
Processing file 1fIHUYC8_fdDQxc94ll3c8ogtPJwMloP6 00012.npy
Processing file 1x6WgO6KkPO30M7z_LSc1fUcoRVXWpMNf 00013.npy
Processing file 17sYNe1Kba2UzABi5isUhEY4grHVGjQ2- 00014.npy
Processing file 1PSe_51__n7Hn4WRR4rrJ1klNX6zD86Qw 00015.npy
Processing file 1pp-Xm5jCCJzpj6QWJFebKdOHW1Kr6m5U 00016.npy
Processing file 1NHqs42s5AZNLEXiNimi41gVPeFLvcVP3 00017.npy
Processing file 1nz7F0OnCLsSO_ltdsQGzAvC6C25u86iO 00018.npy
Processing file 11T3gWC6h-K58AF0uL_4tVB7bRPjJudQg 00019.npy
Processing file 1RYV-8_ojQ69J2u5_2rlX66zrl2_OCz0D 00020.npy
Processing file 12hTs82zKqVtxUldXAX3UUoNQrTqRsS5h 00021.npy
Processing file 1a7lFcpYQiMNxwWTm27-rMTaSQZ5rRMit 00022.npy
Processing file 1R_ewl1ihbd39157YbUDDrfUzr9j7051Z 00023.npy
Processing file 16_qzkjhtYrDQip9ISptTHeegSNvq3ePC 00024.npy
Processing file 1gkk5GcyD04Zwdo5TEEnvfp_ZIJLMi-sg 00025.npy
Processing file 1PgEVxc-8Z10BNhpG1o3V_XxAYmu4Y6BT 00026.npy
Processing file 1-7MXII3l0cNjRmFoumPSYNldaiizq2jK 00027.npy
Processing file 1RdPwj5X58mX1EE7jnc3EnOnwt9BXmSd9 00028.npy
Processing file 1KSHYKgseZUdzxNdlXmpYllXZ0LiAgiMV 00029.npy
Processing file 1fAID5dPR8seAAOidbgfirWHqHjbv3gq8 00030.npy
Processing file 1IIllWL5tl5Ww5-uh-7PGejmRml1vF6gc 00031.npy
Processing file 1JXM2roiQKU_uKhZzhz8xpG3sWtCZUsKa 00032.npy
Processing file 1R43bkdVK0CZ-C-xqtmtDgpec3T2Dg9nH 00033.npy
Processing file 1jxVX4sdjvkY-8sBcHsUItLHRYc1whsGC 00034.npy
Processing file 1R9HxMTcDuJbcWxfYDH9j1OnYw11M1NoW 00035.npy
Processing file 1LiVcB3qw5sOR2kyXWjB5cdb4RgjPdcXn 00036.npy
Processing file 1sdeIT35UTMiwD72yXKS-Xu0fkCHx4pym 00037.npy
Processing file 1y9qvzjPzIh8gpR0lEcI6rF0fo7WhqCYY 00038.npy
Processing file 1zR0RGJKYkYLbaNgXsA5ZGuaE2g3u4x5- 00039.npy
Processing file 1uGBIp4NJoLU6cvwR3zYgOtgcOvD97Bnt 00040.npy
Processing file 1kxthsaGJc9fs1wWI0ND494meVOsmdR8Q 00041.npy
Processing file 1G0WtVYzCIoLvHsq1gozuGaYRxX8gPiVG 00042.npy
Processing file 1oqJ0eaU30BCxh_7ifl5zJWMJ2lbsUmQ6 00043.npy
Processing file 1FeLaS9RC8GyFlzC7bAFsv8GqBfLKRp3b 00044.npy
Processing file 19hzl5p4sS0NEoHC-8C0EXWiYizTQqR1_ 00045.npy
Processing file 14Cg0wxYJNUjPlt0XmSdhBfa8DPyw62EO 00046.npy
Processing file 1FlbMcT3Azo-hc0V2fPIhYUCrNnmXTLjA 00047.npy
Processing file 1832maT_RL74fstMmN5_13OR6kO6rpu5b 00048.npy
Processing file 1l2O_kfeDkbXs2FkNE1UZOsLMY9Pt2Kza 00049.npy
Retrieving folder 1dTklQdRXQP8-P4E8B5zlUpg2IJQdIk_F Scene06
Processing file 1DiP8Aqfh7BtrDzT82ZjTAY_vphgJI0CC 00000.npy
Processing file 1pVkbb_KsmJxtM2fypI7UoNRuRnej-4e0 00001.npy
Processing file 1OcB1rSIeAfknnfK2NlgYBZfbTqORz8Qg 00002.npy
Processing file 1ekw7zGVKFGQe7C_bdlPMo69jgzKbH7NK 00003.npy
Processing file 1kdOpnJbY6FnsHVr62KMfszT8Kcau8LY0 00004.npy
Processing file 14mK__JJn0lX9WUaqpJelYsUpg3XFaTP7 00005.npy
Processing file 1QJtlUV3RD0T3ya1xklUfxAeV940JNQyp 00006.npy
Processing file 1knE2eXO9UiBB0fyST9Rm4GXESxQLTRfY 00007.npy
Processing file 1V-WycFYhx43IzB7zclHzgQj_gkh7YyHj 00008.npy
Processing file 1VbxV7yPnmeMubbF4Phmb4ZdnUSYUqO79 00009.npy
Processing file 12GfzECK3fCrAtHKoOfLKksMBDQR4vOVb 00010.npy
Processing file 16eYHy3MTnZoU9E7CJbdI4c1aUeeGCQmQ 00011.npy
Processing file 1_HZw2eA-bOuU-CkWoucYScrIU7nQWrpt 00012.npy
Processing file 1bzE55gC8HJzsjd0yPPq3m3cVkYPDllM1 00013.npy
Processing file 1P04jGQLz5rTdTeQKC8BvieuHRZCwDrNB 00014.npy
Processing file 10r7C03kQ76X4qWwJBu85lpWdRoYofrWj 00015.npy
Processing file 1xMgcMoz3pULRTxsh8NS7gCVLlTnlmjQz 00016.npy
Processing file 17JwvJd0GkvX58zodqyPfX1o_4KG5lbCp 00017.npy
Processing file 1oFuVWo5D_r73mojqosHKEMNNboP5exmg 00018.npy
Processing file 1xixCzusYp2SpG-BZhAGNAgd_We7VgJVc 00019.npy
Processing file 1hcKW6f6E3oloMs7e0LNwSzJQiSBTaLcR 00020.npy
Processing file 1FRom5tSUsljkbZ0QY-IZgUAqUwwUyIEq 00021.npy
Processing file 1ahREcJRfMgtKC0ZVQlVAPT1nqD9MkZwr 00022.npy
Processing file 1taymyH13oKdC1Qpxlt5HAhul2gqhXHIO 00023.npy
Processing file 1lWf04PlF0EAkdg4Lm_xb9ZjUstGvg4Mj 00024.npy
Processing file 1OQDViETij3EC6pg3EnJhyVtA2WikAvvX 00025.npy
Processing file 1_xaS6Fgtat06_cBxZKX-DF_Q_slKJJ9C 00026.npy
Processing file 1KsaCtEUkPwTVyCicWHeVDh4O3Yaz-x5o 00027.npy
Processing file 1WS6JmOLofA483PQiirrsxnGlkfKUVDWS 00028.npy
Processing file 18xDfdtgCVRI_VFSoxB7cSgK5IXBNJZ2k 00029.npy
Processing file 1oVtgnkXcUkPvpEoQkfhpm0r3_UT0mUVT 00030.npy
Processing file 1WvEvmA2A2eloOWz-nJLZmuI2iTXSvkKB 00031.npy
Processing file 1QOaN8MsBknMmLQTChSedEI3t6-ofBBj7 00032.npy
Processing file 1tfZbbhS7FT2w2dY5FUGg1hkEsSD3mzi6 00033.npy
Processing file 1adeZNuHqyBodlq7Y-Ed5HBJO1142YqjA 00034.npy
Processing file 1WcsD_1qHjSo0ppXx6GOULPf-8HTjOg1R 00035.npy
Processing file 1NtFIIQ8i2nxXE0c-m-KnUKKQpnyxnhOV 00036.npy
Processing file 1YF6J2gUNiPBLgdj_6dplFtSfYJIluupn 00037.npy
Processing file 1zm5YPtgrqHwzY3HOUbKY1VsHkhvHWZPn 00038.npy
Processing file 1wJN4Au4IKRSx0lp6PrTJmcKGWD70ngeK 00039.npy
Processing file 1zHGCsJVoXoH4br386Rxn9v7z4Uduiqoj 00040.npy
Processing file 1gslbi-10dER-sDCle2waFSau8JE3kIPx 00041.npy
Processing file 1NH96PdQrS-FhIf3m3WlrfXA904LF05V5 00042.npy
Processing file 1EqQF9HkmrzeDOSgJOuCX59F0u5qE2Yq1 00043.npy
Processing file 1b1mXTRbY4fZrrOPkFhATZmFnEswCugA9 00044.npy
Processing file 1ad-xSxsyJl9CAAGPcIjHtl8ho3N5l-KX 00045.npy
Processing file 1bonBphUAcSXlYRqxw1KElfOXKuWUzaIs 00046.npy
Processing file 1GJeuANkQmNf2swmAmtFOREA2YEfdyfyO 00047.npy
Processing file 1lxryMP8kitBFnfQhH-aAeTe8CZDdzGka 00048.npy
Processing file 1ZMQtpp9E-hMfsaj12FIBn-loPGteIeZD 00049.npy
Retrieving folder 1X7owBaH16vBrLZTS4sySAHNDLwJ-DKRm Scene18
Processing file 1FuCte63P_1L0OSj62NQWe56bB24fTf9B 00000.npy
Processing file 17KxqxMOyp0AhzFoN7x5XndtBtKmHmdZU 00001.npy
Processing file 1zcFXzlt6X_IPMJ_dKmIYZKURwiTHuwKz 00002.npy
Processing file 1ex040BQ6mWBBfgmBIiFl3LgLru0Sl23O 00003.npy
Processing file 1AqwIyBRFN5XU8Kw58Ezu9GhE7YXMtZ_C 00004.npy
Processing file 1Ke26ipIBGcE6LW_oDYH6rAQwyf3zQcfZ 00005.npy
Processing file 13uIvTbZklWLuHGaZTMdjuMIeaJlWJpQC 00006.npy
Processing file 11rVMTZ_w49JU_Tjahe9K4BlK92uW8SqH 00007.npy
Processing file 1PaOtATB_6rRUnH_0XncYVJTW0QsjtyPV 00008.npy
Processing file 1aEYwyuSeKYWEkhEbJoc8RPPuJ3c1sMMb 00009.npy
Processing file 12A3FtKENU7fDRUnDTf19KnEOGaIe_flZ 00010.npy
Processing file 1dO9Hm52b0ljZgVKLurXwD7c5ZXR10ImF 00011.npy
Processing file 11-_0kvK4PcJBX4Ecpr-NQVPavgAoiYnl 00012.npy
Processing file 1bkk1wt8UYZOMzHpKKJY3--hHdpVoKQu3 00013.npy
Processing file 1fCoIuldIvE8pJPhwiteRWjSzQBZ2ZLa1 00014.npy
Processing file 1PiMC0rlG9jADyv01gHr7dAKJCnBslS-c 00015.npy
Processing file 12Vh9xKHYcOM9VoxQ-fMRnZ042xssBuwJ 00016.npy
Processing file 1LulkK0fjcqy2ziMJKVaPKoRJfLEjjLFM 00017.npy
Processing file 1gWoGobZ7cGVRB1NIlZE3m9LW_DvaqS5X 00018.npy
Processing file 1VokroWhH7aw_-K4FqGUDmaHy9ztL_myB 00019.npy
Processing file 1CRXqGwjHPqCxZhOiwixiXkjbhCE-ME71 00020.npy
Processing file 1XRMRvl2LVruIiI2MNC8dgFDjJS5GW0MR 00021.npy
Processing file 1xeuusJMIEpWdsfjrrKg21k-TX_j7bziy 00022.npy
Processing file 1h1pbcOe0VNJKEmqHPs4Xf2oA_rHbR29e 00023.npy
Processing file 10XixTh5qKxbCM-aX8570SCWdO_NqZxXk 00024.npy
Processing file 1PBu2aL1iZkDiglGy1AX7C1tEhsl1AWFG 00025.npy
Processing file 1INud4mKOUyBCdnbF-2h158eAWOQpn0Jq 00026.npy
Processing file 1UBC814D6cjeV4Yyn4TzJrn1IZRUWByKg 00027.npy
Processing file 1I-Oz5RSuMkBzrhRRurcR3mmyo6Y_SI_O 00028.npy
Processing file 1hwqHd1Kz20fUhIMvBwUxKdhBmPrnudoM 00029.npy
Processing file 1girlrXHYy9UIP7Croh0T3mU8qQNNUkt1 00030.npy
Processing file 1AMlfwkfWSk3-sCL_ajxGbFGPQOLExrox 00031.npy
Processing file 1gu4S3cvrS_CIW4kocmK_RNclWE9Lk8Ap 00032.npy
Processing file 1Qm2PV4kKc5SCjPz5fd105qmWtVeiV1dk 00033.npy
Processing file 1ZDGAUovWfOxJT1-Ss-knCvutM1PhtYGX 00034.npy
Processing file 1oSlWdwgygyU6muwB_XliarpN_GRdOFZ6 00035.npy
Processing file 1lgPMRebNndDYa2QQrqAPbqh3pcICXLtd 00036.npy
Processing file 1-zkpQiGcrhwK25p3v6tPwJQ8T5RsCS1g 00037.npy
Processing file 1B19ZlHAwgkVmpE1yFSUFqRYQCBDqCz5r 00038.npy
Processing file 16lIT8YEY_MGWlEuZ9ia54P0fw3XL7aE0 00039.npy
Processing file 1ajJFYrSpynWSIuZWafE1O4P3y-psFxyR 00040.npy
Processing file 17clHMS2_QmQGWyJqsOxL9pj2l09DdfQO 00041.npy
Processing file 1NyOru3EHKzhkqNC9PH2EBMZp21rIUbH3 00042.npy
Processing file 1QaN_lVL9vfgJ0eAByuhmL6Hn4rHynbHI 00043.npy
Processing file 1_y7JhtFDV9QNJH4S37VU4uT-ndabk-N7 00044.npy
Processing file 14HXpoZvqAnSuscT2zkZJqDK-qld8BXsy 00045.npy
Processing file 1ri4uFd0XJAl_SbHA71aW64AOIO4GdbPQ 00046.npy
Processing file 1gVzPVrqnlCrDFjJWQKn468oR1mLf1Ahl 00047.npy
Processing file 1Zna-OSm54zhEjVLI06IZQ3_bd0rR-qBa 00048.npy
Processing file 1n6FJHBnTrUDd2UAbG8LDYw4-Ou40-5nC 00049.npy
Retrieving folder 1EduS3ilLx-ho1v9OdX5WmvirvyykBlZA Scene20
Processing file 1h5GPk5967zlQE01HuswK6WSnWVYEzIFF 00000.npy
Processing file 1SEK_V62WeVZ-cUkTjKysVZqY0W1RLOal 00001.npy
Processing file 1LINHNKaKd-hrTSJvv31g95oDWebc1S_c 00002.npy
Processing file 1u06CCX4nobD16OJob3959XowfonZ2zw_ 00003.npy
Processing file 1sXoZJFl4CyUHjQvLZa-Sw1oubtbA3wY1 00004.npy
Processing file 14njEvoiq2AWSGkkwBP_pGNObqNE292Cq 00005.npy
Processing file 1neJNX4hRNZy9PmKSQpNfiv8BTU9RA8-E 00006.npy
Processing file 1JtKdJLsb2EDc8GHxfKxWtu_wnfDBqujO 00007.npy
Processing file 1ALYvdFJPkxJ7dTepG4JUzrV6f9M8SDM_ 00008.npy
Processing file 1FW3kI0tnDHVoRSY7oSe-_YV4q2DL7zD- 00009.npy
Processing file 1e3BqIdCB0EiHm00fKvMPsNzt3j4_nOec 00010.npy
Processing file 1jIbthnAN9XGiPhVJ8vqXvWSe1cQv4YcJ 00011.npy
Processing file 19yfblNxemsUcVIuhxfi-UuHMny-Ub7Mv 00012.npy
Processing file 1v_65FzsB7zrrwT17kZp92_FQG6Mb8sj0 00013.npy
Processing file 1TjzhzxOFQTyudSm7GLZGsFsYHGX5VgAn 00014.npy
Processing file 1ZWsfRPkZvt36BXrHMsvCCBOvfCr7bTrN 00015.npy
Processing file 1K8WR-uGMIfuDr2MDJK1kr0m_N-g9mA3u 00016.npy
Processing file 1PHMr1cI4Lw2Q9reBA8R-OzCgK7HBG5o_ 00017.npy
Processing file 17pZGljVbf3cG4cpRapWX3UXbeQiMXIR4 00018.npy
Processing file 1_v3WyS1c4extbuk2BIRkzl1bw0qasVeg 00019.npy
Processing file 1RIS6RLYmvP3BvYEn6chFx0RqzN4j6WId 00020.npy
Processing file 1wwpvQhoAjE2xO-hEFmTXLW9vb30bOtdz 00021.npy
Processing file 1tLZZQ0jNDPFfLrOViIpSTYOl2B8mS6sn 00022.npy
Processing file 1cXkmDt1ePwoj67aTLEKbUIO_W8c3EeYD 00023.npy
Processing file 1NKzUcT8QalJEakB8Fh5rkFYiah_dTZkl 00024.npy
Processing file 1wWOKHsGWrUaSvLvWaCSvsqQ50XuQ7TfW 00025.npy
Processing file 1ujJMz3mv2WcCaZyeYaNkwFVnJyeh2akM 00026.npy
Processing file 1IsnReysvKEx6Y5xS-CmLhKCO0NSUlANL 00027.npy
Processing file 1voATyaZ6Em86SNOQNj_J4KF1_6ty_pG9 00028.npy
Processing file 17AiNtL8GdLaxqyietsMylbsqVoufwXkc 00029.npy
Processing file 1sPTn75brMp9_KykTBI3Hj5bAUzIxIwcV 00030.npy
Processing file 1c3BbGz8cLSdpYZXs5s8XtY4129vHBWGc 00031.npy
Processing file 1ADdgdSRP-2dT6Wq7_6JGvcyFGkxXHGn7 00032.npy
Processing file 1DWkt9XeL_6qT1Gqozloh7I7Y0SM7CpbW 00033.npy
Processing file 1g4obh1SRc1pwiUKEAEV6e1nToqkCSrQq 00034.npy
Processing file 1SSRqLcUaDkcnWgMwlTYoFA1tU6-Fg9AE 00035.npy
Processing file 1pQSr4rd3JB0oTZmsuHNJtOrmE9HaWEfy 00036.npy
Processing file 1jd0YK1-eKDstp7wej8ML2J_f-rHFccKD 00037.npy
Processing file 1BzjkHgvJabw8cQVAOXCLDGzEWAd8epdC 00038.npy
Processing file 1k8LLRaOvnFdVD7MAHgYWCwpU3l3AT7pK 00039.npy
Processing file 1eSYAmY2_b17atgIBRInTqw6agIaqIRbM 00040.npy
Processing file 1xR0iMSCBNAwbvmr3NU7ahimUMyRv4d5A 00041.npy
Processing file 1B0pURssJRqsg9Gq5qg98N5fcSoaAqOrY 00042.npy
Processing file 1vuujPJbH7s0M9hriiIr3lDfChBQhlQ9k 00043.npy
Processing file 1fB0XvgnErIHGVW1CALXuG93CHnYx9WBK 00044.npy
Processing file 1dzf6g2AiZweyD9nYdrxEA00Om-UmEE8z 00045.npy
Processing file 1tE-ZvnZeI3fh7n33ugube3CkktLp_QMU 00046.npy
Processing file 1XQlYO7pM3xBrFuqs109ODcUDq5_jvLWp 00047.npy
Processing file 1jg4V-OnEYMNJLNf85IPyFVYssWA2BRG3 00048.npy
Processing file 1uE884NtiXKNTMjeGBIaHXi75dlhhXiGX 00049.npy
Retrieving folder contents completed
Building directory structure
Building directory structure completed
Failed to retrieve file url:

	Cannot retrieve the public link of the file. You may need to change
	the permission to 'Anyone with the link', or have had many accesses.
	Check FAQ in https://github.com/wkentaro/gdown?tab=readme-ov-file#faq.

You may still be able to access the file from the browser:

	https://drive.google.com/uc?id=10US12kjZXBkIfrmy-bKnDL2XsnPJBwf0

but Gdown can't. Please check connections and permissions.

In [ ]:
!gdown --id 1kkK-qZO-5hwyybCFuaEvANlRXiv-5xxj

/usr/local/lib/python3.12/dist-packages/gdown/__main__.py:139: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  warnings.warn(
Failed to retrieve file url:

	Cannot retrieve the public link of the file. You may need to change
	the permission to 'Anyone with the link', or have had many accesses.
	Check FAQ in https://github.com/wkentaro/gdown?tab=readme-ov-file#faq.

You may still be able to access the file from the browser:

	https://drive.google.com/uc?id=1kkK-qZO-5hwyybCFuaEvANlRXiv-5xxj

but Gdown can't. Please check connections and permissions.

In [ ]:
!gdown 1Ib0Kk8xFoiexv6_9DRnSI58sTQHIDjjS

Downloading...
From (original): https://drive.google.com/uc?id=1Ib0Kk8xFoiexv6_9DRnSI58sTQHIDjjS
From (redirected): https://drive.google.com/uc?id=1Ib0Kk8xFoiexv6_9DRnSI58sTQHIDjjS&confirm=t&uuid=e38d612f-bdfc-4655-8070-67c93357d852
To: /content/vkitti_2.0.3_rgb.tar
100% 7.53G/7.53G [01:30<00:00, 83.2MB/s]

In [ ]:
import os, tarfile


VKITTI_LOCAL = '/content/vkitti2'

os.makedirs(VKITTI_LOCAL, exist_ok=True)


for archive in ['vkitti_2.0.3_rgb.tar', 'vkitti_2.0.3_depth.tar']:

    archive_path = f'/content/{archive}'

    if os.path.exists(archive_path):


        print(f'📦 Распаковываю {archive}...')

        with tarfile.open(archive_path, 'r') as tar:

            tar.extractall(VKITTI_LOCAL)

        print(f'   ✅ Готово')

    else:

        print(f'   ❌ Не найден: {archive}')

📦 Распаковываю vkitti_2.0.3_rgb.tar...

/tmp/ipykernel_23051/3399381077.py:20: DeprecationWarning: Python 3.14 will, by default, filter extracted tar archives and reject files or modify their metadata. Use the filter argument to control this behavior.
  tar.extractall(VKITTI_LOCAL)

   ✅ Готово
📦 Распаковываю vkitti_2.0.3_depth.tar...
   ✅ Готово

In [27]:
!gdown --id  1Dq6kJANt1yvpo3DOqhW-77abl-Gvi5v8

/usr/local/lib/python3.12/dist-packages/gdown/__main__.py:139: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  warnings.warn(
Downloading...
From (original): https://drive.google.com/uc?id=1Dq6kJANt1yvpo3DOqhW-77abl-Gvi5v8
From (redirected): https://drive.google.com/uc?id=1Dq6kJANt1yvpo3DOqhW-77abl-Gvi5v8&confirm=t&uuid=3a62e478-fc33-41bc-9e4b-2166e5be5d79
To: /content/_loader.py
100% 1.90k/1.90k [00:00<00:00, 10.0MB/s]

In [28]:
from _loader import VKITTI2Loader
VKITTI_RGB = '/content/vkitti2'
loader = VKITTI2Loader(VKITTI_RGB)

## продолжеие

In [4]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [6]:
VKITTI_DRIVE = '/content/drive/MyDrive/3dcv-project/data/vkitti2'
VKITTI_LOCAL = '/content/vkitti2'

In [8]:
import os
os.makedirs(VKITTI_LOCAL, exist_ok=True)

In [23]:
import  tarfile

for archive in ['vkitti_2.0.3_rgb.tar', 'vkitti_2.0.3_depth.tar']:

    archive_path = f'{VKITTI_DRIVE}/{archive}'

    if os.path.exists(archive_path):

        print(f'📦 Распаковываю {archive}...')

        with tarfile.open(archive_path, 'r') as tar:

            tar.extractall(VKITTI_LOCAL)

        print(f'   ✅ Готово')

    else:

        print(f'   ❌ Не найден: {archive}')

📦 Распаковываю vkitti_2.0.3_rgb.tar...

/tmp/ipykernel_3227/3785276774.py:13: DeprecationWarning: Python 3.14 will, by default, filter extracted tar archives and reject files or modify their metadata. Use the filter argument to control this behavior.
  tar.extractall(VKITTI_LOCAL)

   ✅ Готово
📦 Распаковываю vkitti_2.0.3_depth.tar...
   ✅ Готово

In [24]:
!cp -r /content/vkitti2 "/content/drive/MyDrive/3dcv-project/data/vkitti2_unpacked"

In [26]:
!ls "/content/drive/MyDrive/3dcv-project/data/vkitti2_unpacked"

 Scene01   Scene06  'Scene18 (1)'  'Scene20 (1)'
 Scene02   Scene18   Scene20	    vkitti2

In [ ]:

!find {VKITTI_LOCAL} -maxdepth 4 -type d | head -30

In [9]:
!ls

drive  sample_data  vkitti2

In [20]:
!ls /content/vkitti2

In [12]:
DEPTH_PRED_DIR = '/content/drive/MyDrive/3dcv-project/results/track_b/depth_pred_vkitti'

In [13]:

print(os.path.exists(DEPTH_PRED_DIR))

True

In [29]:
import matplotlib.pyplot as plt

loader = VKITTI2Loader('/content/vkitti2')

frames = loader.list_frames('Scene01', 'clone')

print(f'Найдено {len(frames)} кадров в Scene01/clone')

Найдено 447 кадров в Scene01/clone

In [30]:
import pandas as pd
from tqdm.notebook import tqdm


results = []

In [31]:
print(DEPTH_PRED_DIR)

/content/drive/MyDrive/3dcv-project/results/track_b/depth_pred_vkitti

In [32]:
for scene in loader.SCENES:

    frames = loader.list_frames(scene, 'clone')

    for frame_id in tqdm(frames, desc=scene):

        gt_depth = loader.load_depth(scene, 'clone', frame_id)

        pred_path = f'{DEPTH_PRED_DIR}/{scene}/{frame_id}.npy'

        if not os.path.exists(pred_path):

            continue

        pred_relative = np.load(pred_path)



        # Если предсказание и GT разного размера — ресайзим

        if pred_relative.shape != gt_depth.shape:

            from PIL import Image

            pred_relative = np.array(Image.fromarray(pred_relative).resize(

                (gt_depth.shape[1], gt_depth.shape[0])))



        # Калибровка

        mask = (gt_depth > 0.1) & (gt_depth < 80)

        if mask.sum() < 100:

            continue

        pred_metric, _, _ = align_depth_lstsq(pred_relative, gt_depth, mask)



        # Метрики

        m = compute_depth_metrics(pred_metric, gt_depth)

        m['scene'] = scene

        m['frame'] = frame_id

        results.append(m)

df = pd.DataFrame(results)

df.to_csv('/content/drive/MyDrive/3dcv-project/results/track_b/B3_depth_metrics_vkitti.csv',

          index=False)

print('n📊 Сводка по VKITTI2:')

print(df[['AbsRel', 'RMSE', 'δ < 1.25']].mean())

Scene01:   0%|          | 0/447 [00:00<?, ?it/s]

/tmp/ipykernel_3227/1536373973.py:23: RuntimeWarning: invalid value encountered in log
  rmse_log = np.sqrt(np.mean((np.log(pred) - np.log(gt)) ** 2))

Scene02:   0%|          | 0/233 [00:00<?, ?it/s]

Scene06:   0%|          | 0/270 [00:00<?, ?it/s]

Scene18:   0%|          | 0/339 [00:00<?, ?it/s]

Scene20:   0%|          | 0/837 [00:00<?, ?it/s]

n📊 Сводка по VKITTI2:
AbsRel      0.506330
RMSE        9.725141
δ < 1.25    0.390757
dtype: float64

In [37]:
scene_summary = (
    df.groupby('scene')[['AbsRel', 'RMSE', 'δ < 1.25']]
      .mean()
      .round(3)
)

scene_summary.columns = [
    'AbsRel ↓',
    'RMSE ↓',
    'δ < 1.25 ↑'
]

styled = (
    scene_summary.style
    .format('{:.3f}')

    # Лучшие значения
    .highlight_min(
        subset=['AbsRel ↓', 'RMSE ↓'],
        color='#d9ead3'
    )
    .highlight_max(
        subset=['δ < 1.25 ↑'],
        color='#d9ead3'
    )

    # Худшие значения
    .highlight_max(
        subset=['AbsRel ↓', 'RMSE ↓'],
        color='#f4cccc'
    )
    .highlight_min(
        subset=['δ < 1.25 ↑'],
        color='#f4cccc'
    )

    .set_caption("Сводка метрик по сценам VKITTI2")
)

styled

для AbsRel и RMSE
- маленькое значение → хорошо → зелёное
- большое значение → плохо → красное


для δ < 1.25
- большое значение → хорошо → зелёное
- маленькое значение → плохо → красное

In [38]:
scene_summary = (
    df.groupby('scene')[['AbsRel', 'RMSE', 'δ < 1.25']]
      .mean()
      .round(3)
)

styled = (
    scene_summary.style
    .format({
        'AbsRel': '{:.3f}',
        'RMSE': '{:.3f}',
        'δ < 1.25': '{:.3f}'
    })
    .set_caption("Сводка метрик по сценам VKITTI2")
    .set_table_styles([
        {
            'selector': 'caption',
            'props': [
                ('font-size', '14px'),
                ('font-weight', 'bold'),
                ('text-align', 'center')
            ]
        },
        {
            'selector': 'th',
            'props': [
                ('font-weight', 'bold'),
                ('text-align', 'center')
            ]
        },
        {
            'selector': 'td',
            'props': [
                ('text-align', 'center')
            ]
        }
    ])
)

styled

In [33]:
df.to_csv(
    '/content/drive/MyDrive/3dcv-project/results/track_b/B3_depth_metrics_vkitti.csv',
    index=False
)

print("Файл сохранён")

Файл сохранён